#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;

$root = ($word) <1-5> ;

$obecny = (a {a}| be {b} | ce {c} | de {d} | e {e}| ef {f} | gie {g} | ha {h})
        (jeden {1} | dwa {2} | trzy {3} | cztery {4} | pięć {5} | sześć {6} | siedem {7} | osiem {8});
$docelowy = (a {a}| be {b} | ce {c} | de {d} | e {e}| ef {f} | gie {g} | ha {h})
        (jeden {1} | dwa {2} | trzy {3} | cztery {4} | pięć {5} | sześć {6} | siedem {7} | osiem {8});

$word = (król | hetman | wieża | goniec | skoczek | pion | [mała] roszada | [duża] roszada) [z] ($obecny) [na] ($docelowy);







