from tts.call_synthesize import call_synthesize
from address_provider import AddressProvider
from dictation.dictation_client import create_audio_stream, print_results
from dictation.service.dictation_settings import DictationSettings
from dictation.service.streaming_recognizer import StreamingRecognizer
from os.path import join as opjoin